train_data_path: "./data/TurtleBench-extended-en/train_8k.json"
test_data_path: "./data/TurtleBench-extended-en/test_1.5k.json"
prompt_path: "./prompts/prompt_en.json"
template: "Based on the judgment rule, this player's guess is [MASK]"

pretrained_model_path: "bert-large-uncased"
batch_size: 2
epochs: 10
learning_rate: 1e-5
weight_decay: 1e-4

pet:
    max_length: 512
    enable_contrastive_learning: false
    lambda_weight: 0.5
    contrastive_margin: 1.0
    label_map: { T: "correct", F: "incorrect", N: "unknown" }

classification:
    max_length: 512
    label_map: { T: 0, F: 1, N: 2 }

contrastive:
    max_length: 256
    contrastive_margin: 1.0

output_dir: output/en
